services:
  educhat:
    build: ./educhat
    container_name: educhat
    ports:
      - "8080:8080"

  ms-gamification:
    build: ./ms-gamification
    container_name: ms-gamification
    ports:
      - "8081:8081"